apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 3000 