apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - name: pong
          image: teeh/pong
          env:
          - name: DATABASE_URL
            valueFrom:
               secretKeyRef:
                name: pong-secrets
                key: DATABASE_URL