apiVersion: v1
kind: Service
metadata:
  name: pong-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: pong
  ports:
    - name: http
      protocol: TCP
      port: 1234 
      targetPort: 8000 