apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: project
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:IKl3XnmkJbN6VcGF,iv:x/8BtzkZ/2gbHXEmFSSpmmGWI7hML0++DC7L7U4BM4o=,tag:kzuxxafStO/cyfii2ieEKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y6n4ghqmtks65d9mem0kw9dtdqzuqghs2wjqrskln27k7znc7yts3f3fee
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBra0tQRGNZV0MvWm51UkFI
            MlpEZDF6ckhvU3FWcUFjT0RZS1VLcS90WWs4ClV4bG9EQ1pjRDhRcXg5eVp5VndU
            YjJxTnh0T1llMGpGSExSM09INEN3dFUKLS0tIGJwMFUrV2dhazZ3YTBweFR6cHRS
            enVxWHJldzJ4aGFoSEtka0RNaWNyY28K45whG27zZZSXoKgNuPhIjwOG4usMqnup
            R7KPwmPQ4XpXtj/X5XxeIkxjPFuXgwsPP7qE4eGJb2t43uz1bI/RGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-09T18:10:56Z"
    mac: ENC[AES256_GCM,data:ORGLMZWH3kedIv5DB2X4PIQV0ZgcTSn2d3m9j13mTcWsnXJOrGehZYBtZuHOEfYTCWpoNoUID7SjuWRu1KBZORoWClfjPuwzF9RSTThHVfmzDWmBKdPYhK6cbMincV7wU+reeQMtpCdZaH4rGXJURHJjWuzB1/ncC74tKynzx5c=,iv:TlXXywmIn9TFf5RRTz1J6dkLqmXENXaVTA9bQMuWT1c=,tag:ejn06evOgITE8fPJab1VEg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
