apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes: # Define volume
        - name: shared-file
          persistentVolumeClaim:
            claimName: ponglog
      containers:
        - name: reader
          image: teeh/reader
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: helloconfig
                  key: MESSAGE
          volumeMounts: # Mount volume
          - name: shared-file
            mountPath: /usr/src/app/files
        - name: writer
          image: teeh/writer
          volumeMounts: # Mount volume
          - name: shared-file
            mountPath: /usr/src/app/files