apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      volumes: # Define volume
        - name: shared-file
          persistentVolumeClaim:
            claimName: ponglog
      containers:
        - name: pong
          image: teeh/pong
          volumeMounts: # Mount volume
          - name: shared-file
            mountPath: /usr/src/app/files