apiVersion: batch/v1
kind: CronJob
metadata:
  name: dailytodo
  namespace: project
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dailytodo
            image: teeh/dailytodo
            env:
              - name: TODO_BACKEND
                value: "http://todo-svc/todos"
          restartPolicy: Never