apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      volumes: 
        - name: images
          persistentVolumeClaim:
            claimName: ponglog
      containers:
        - name: web-server
          image: teeh/webserver
          volumeMounts: # Mount volume
          - name: images
            mountPath: /usr/src/app/public/images