apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images
  namespace: project
spec:
  storageClassName:  local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi